### ISSUE TITLE
OpenAI error message received when attempting to ask a question about a YouTube video

### ISSUE THREAD

**Issue by Shivraj-K09** [arian0zen/QueryWhisperer#2]
I am experiencing an issue while using this platform to ask a question about a YouTube video. After successfully pasting the video link in the transcription field and receiving a success message, I attempted to ask a question but received the following error message: "Ohh hoo! Probably my OpenAI trial is over, hey! Would you sponsor me ? 🙌". This error occurred consistently during my testing of the platform.

**Comment by arian0zen** [comment]
probable reasons: 
a. openAI api key not configured correctly
b. pinecone index and api not configured correctly

**Comment by arian0zen** [comment]
the pinecone index name was hardcoded(as my pinecone index name) at one place, that was causing the issue
it has been fixed :) 🙌
